Repository RehanSaeed/Serilog.Exceptions, pull requests merged in 2021-06, with the labels that each got.

#358 Update global.json to .NET 5.0.301
  global.json
Labels: maintenance, patch

#362 Add NuGet Package Downloads
  README.md
Labels: documentation, patch

#363 Use ConcurrentDictionary instead of lock
  Source/Serilog.Exceptions/Reflection/ReflectionInfoExtractor.cs
Labels: enhancement, patch
