Repository RehanSaeed/Serilog.Exceptions, pull requests merged in 2021-11, with the labels that each got.

#375 Configuration example
  README.md
Labels: patch, documentation

#429 Bump .editorconfig & use file scoped namespaces
  .editorconfig
  Benchmarks/Serilog.Exceptions.Benchmark/BenchmarkException.cs
  Benchmarks/Serilog.Exceptions.Benchmark/BenchmarkExceptionDestructurer.cs
  Benchmarks/Serilog.Exceptions.Benchmark/DestructuringBenchmark.cs
  Benchmarks/Serilog.Exceptions.Benchmark/ExceptionPropertiesBag.cs
  Benchmarks/Serilog.Exceptions.Benchmark/Point.cs
  Benchmarks/Serilog.Exceptions.Benchmark/Program.cs
  Source/Serilog.Exceptions.EntityFrameworkCore/Destructurers/DbUpdateExceptionDestructurer.cs
  Source/Serilog.Exceptions.MsSqlServer/Destructurers/SqlExceptionDestructurer.cs
  Source/Serilog.Exceptions.Refit/Destructurers/ApiExceptionDestructurer.cs
  Source/Serilog.Exceptions.SqlServer/Destructurers/SqlExceptionDestructurer.cs
  Source/Serilog.Exceptions/Core/DestructuringOptionsBuilder.cs
  Source/Serilog.Exceptions/Core/ExceptionEnricher.cs
  Source/Serilog.Exceptions/Core/ExceptionPropertiesBag.cs
  Source/Serilog.Exceptions/Core/IDestructuringOptions.cs
  Source/Serilog.Exceptions/Core/IExceptionPropertiesBag.cs
  Source/Serilog.Exceptions/Destructurers/AggregateExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/ArgumentExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/ArgumentOutOfRangeExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/ExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/IExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/OperationCanceledExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/ReflectionBasedDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/ReflectionTypeLoadExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/SocketExceptionDestructurer.cs
  Source/Serilog.Exceptions/Destructurers/TaskCanceledExceptionDestructurer.cs
  Source/Serilog.Exceptions/DictionaryExtensions.cs
  Source/Serilog.Exceptions/Filters/CompositeExceptionPropertyFilter.cs
  Source/Serilog.Exceptions/Filters/IExceptionPropertyFilter.cs
  Source/Serilog.Exceptions/Filters/IgnorePropertyByNameExceptionFilter.cs
  Source/Serilog.Exceptions/LoggerEnrichmentConfigurationExtensions.cs
  Source/Serilog.Exceptions/Reflection/ReflectionInfo.cs
  Source/Serilog.Exceptions/Reflection/ReflectionInfoExtractor.cs
  Source/Serilog.Exceptions/Reflection/ReflectionPropertyInfo.cs
  Source/Serilog.Exceptions/TypeExtensions.cs
  Tests/Serilog.Exceptions.Test/Destructurers/AggregateExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ApiExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ArgumentExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ArgumentNullExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ArgumentOutOfRangeExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/DbUpdateExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ExceptionPropertiesBagTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/LogJsonOutputUtils.cs
  Tests/Serilog.Exceptions.Test/Destructurers/OperationCanceledExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/ReflectionBasedDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/SocketExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/Destructurers/TaskCanceledExceptionDestructurerTest.cs
  Tests/Serilog.Exceptions.Test/DictionaryExtensionsTest.cs
  Tests/Serilog.Exceptions.Test/Filters/CompositeExceptionPropertyFilterTest.cs
  Tests/Serilog.Exceptions.Test/Reflection/ReflectionInfoExtractorTest.cs
  Tools/ExceptionFinderTool/Program.cs
Labels: maintenance, patch

#430 Bump Microsoft.SourceLink.GitHub from 1.0.0 to 1.1.0
  Source/Directory.Build.props
Labels: enhancement, patch

#431 Bump Microsoft.VisualStudio.Threading.Analyzers from 17.0.63 to 17.0.64
  Directory.Build.props
Labels: maintenance, patch

#436 Fix images in embedded NuGet package README.md
  README.md
Labels: patch, documentation

#435 Upgrade Windows image to VS 2022
  appveyor.yml
Labels: maintenance, patch

#438 Bump Cake.Tool from 1.3.0 to 2.0.0
  build.cake
  dotnet-tools.json
Labels: maintenance, patch
